### PR TITLE
Add margin and padding

### PR DESCRIPTION
**Pull request by artnez**

### CODE REVIEW

**Comment by steadicat** [comment]
I don't know how I feel about adding short-hands quite yet. Why these two and not all the others? Do we need a strategy to merge short-hands with regular properties or can we let them all through and let the DOM handle it?

From a stylistic convention perspective I have reservations too. Should we encourage components to use short-hands like `margin="0 30px"` when what they really mean is `marginLeft={30} marginRight={30}`? I could see someone using the former because of laziness, accidentally specifying vertical margins, which might prevent other components from overriding those.

**Comment by artnez** [comment]
I actually wrote a new approach for handling short-hands but it breaks the CSS spec. It worked like this:

``` javascript
const groups = {
  margin: ['marginTop', 'marginRight', 'marginBottom', 'marginLeft'],
  padding: ['paddingTop', 'paddingRight', 'paddingBottom', 'paddingLeft'],
  borderWidth: [... etc ...],
  etc...
};

// When applying styles loop groups too and apply the value to all style keys in the group.
```

The above could be simplified (eg: to reduce function) but that's the general idea.

**Comment by artnez** [comment]
I think we should definitely have short-hands though. Some ideas to keep this library from bloating:
- Add a plugin API. `extract()` can take a second argument which would act as a fallback function. We can write a separate library (eg: `stylistic-extras`) that adds short-hands and other things. Benefit: library stays small and simple. Drawback: more NPM.
- Name the short-hands something else like `marginAll`. Benefit: batteries included. Drawback: bloat.

**Comment by artnez** [comment]
Oh and we can combine both options by including an extras module with this library for opt-in bloat :man:

**Comment by steadicat** [comment]
How would that strategy work for things like `font` (`[weight] [style] [size]/[line-height] [family]`) or `border` (`[width] [style] [direction]`)?

I like the idea of short-hands but I wonder if the CSS way is the best way. I'd consider something more React-y like `{...margin(1, 'red')}`. You could use a separate library for those, or write custom ones for your project, as many as you like.

**Comment by artnez** [comment]
Is this outside the scope of the library anyway? Why not just pass through all CSS properties and let the developer choose? Any pitfalls?

**Pull request merged**
